# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_main_engckTDTB.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(860, 706)
        Form.setMaximumSize(QSize(860, 725))
        self.tabWidget = QTabWidget(Form)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(11, 160, 840, 241))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.layoutWidget = QWidget(self.tab)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(12, 13, 307, 158))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_67 = QLabel(self.layoutWidget)
        self.label_67.setObjectName(u"label_67")
        font = QFont()
        font.setPointSize(8)
        self.label_67.setFont(font)
        self.label_67.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_67, 0, 0, 1, 1)

        self.label_68 = QLabel(self.layoutWidget)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setFont(font)
        self.label_68.setToolTipDuration(-1)
        self.label_68.setAutoFillBackground(False)

        self.gridLayout.addWidget(self.label_68, 1, 0, 1, 1)

        self.hw_id = QLineEdit(self.layoutWidget)
        self.hw_id.setObjectName(u"hw_id")

        self.gridLayout.addWidget(self.hw_id, 1, 1, 1, 1)

        self.label_69 = QLabel(self.layoutWidget)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setFont(font)
        self.label_69.setToolTipDuration(-1)
        self.label_69.setAutoFillBackground(False)

        self.gridLayout.addWidget(self.label_69, 2, 0, 1, 1)

        self.hw_id_2 = QLineEdit(self.layoutWidget)
        self.hw_id_2.setObjectName(u"hw_id_2")

        self.gridLayout.addWidget(self.hw_id_2, 2, 1, 1, 1)

        self.label_70 = QLabel(self.layoutWidget)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setFont(font)
        self.label_70.setToolTipDuration(-1)
        self.label_70.setAutoFillBackground(False)

        self.gridLayout.addWidget(self.label_70, 3, 0, 1, 1)

        self.sw_id = QLineEdit(self.layoutWidget)
        self.sw_id.setObjectName(u"sw_id")

        self.gridLayout.addWidget(self.sw_id, 3, 1, 1, 1)

        self.label_71 = QLabel(self.layoutWidget)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setFont(font)
        self.label_71.setToolTipDuration(-1)
        self.label_71.setAutoFillBackground(False)

        self.gridLayout.addWidget(self.label_71, 4, 0, 1, 1)

        self.sw_ver = QLineEdit(self.layoutWidget)
        self.sw_ver.setObjectName(u"sw_ver")

        self.gridLayout.addWidget(self.sw_ver, 4, 1, 1, 1)

        self.label_72 = QLabel(self.layoutWidget)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setFont(font)
        self.label_72.setToolTipDuration(-1)
        self.label_72.setAutoFillBackground(False)

        self.gridLayout.addWidget(self.label_72, 5, 0, 1, 1)

        self.sw_date = QLineEdit(self.layoutWidget)
        self.sw_date.setObjectName(u"sw_date")

        self.gridLayout.addWidget(self.sw_date, 5, 1, 1, 1)

        self.tabWidget.addTab(self.tab, "")
        self.b097 = QWidget()
        self.b097.setObjectName(u"b097")
        self.line_9 = QFrame(self.b097)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(23, 30, 20, 175))
        self.line_9.setFrameShape(QFrame.VLine)
        self.line_9.setFrameShadow(QFrame.Sunken)
        self.label_47 = QLabel(self.b097)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(11, 11, 139, 16))
        self.label_47.setFont(font)
        self.label_47.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_44 = QLabel(self.b097)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(40, 77, 31, 16))
        self.label_44.setFont(font)
        self.byte097hbit2 = QCheckBox(self.b097)
        self.byte097hbit2.setObjectName(u"byte097hbit2")
        self.byte097hbit2.setEnabled(False)
        self.byte097hbit2.setGeometry(QRect(10, 77, 16, 16))
        self.label_62 = QLabel(self.b097)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(40, 187, 31, 16))
        self.label_62.setFont(font)
        self.label_62.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.byte097hbit0 = QCheckBox(self.b097)
        self.byte097hbit0.setObjectName(u"byte097hbit0")
        self.byte097hbit0.setEnabled(False)
        self.byte097hbit0.setGeometry(QRect(10, 33, 16, 16))
        self.byte097hbit4 = QCheckBox(self.b097)
        self.byte097hbit4.setObjectName(u"byte097hbit4")
        self.byte097hbit4.setEnabled(False)
        self.byte097hbit4.setGeometry(QRect(10, 121, 16, 16))
        self.byte097hbit4.setChecked(False)
        self.label_42 = QLabel(self.b097)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(40, 165, 31, 16))
        self.label_42.setFont(font)
        self.label_42.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.byte097hbit6 = QCheckBox(self.b097)
        self.byte097hbit6.setObjectName(u"byte097hbit6")
        self.byte097hbit6.setEnabled(False)
        self.byte097hbit6.setGeometry(QRect(10, 165, 16, 16))
        self.byte097hbit7 = QCheckBox(self.b097)
        self.byte097hbit7.setObjectName(u"byte097hbit7")
        self.byte097hbit7.setEnabled(False)
        self.byte097hbit7.setGeometry(QRect(10, 187, 16, 16))
        self.label_57 = QLabel(self.b097)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(40, 33, 31, 16))
        self.label_57.setFont(font)
        self.label_57.setToolTipDuration(-1)
        self.label_57.setAutoFillBackground(False)
        self.byte097hbit3 = QCheckBox(self.b097)
        self.byte097hbit3.setObjectName(u"byte097hbit3")
        self.byte097hbit3.setEnabled(False)
        self.byte097hbit3.setGeometry(QRect(10, 99, 16, 16))
        self.label_63 = QLabel(self.b097)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(40, 121, 31, 16))
        self.label_63.setFont(font)
        self.byte097hbit1 = QCheckBox(self.b097)
        self.byte097hbit1.setObjectName(u"byte097hbit1")
        self.byte097hbit1.setEnabled(False)
        self.byte097hbit1.setGeometry(QRect(10, 55, 16, 16))
        self.label_65 = QLabel(self.b097)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(40, 99, 31, 16))
        self.label_65.setFont(font)
        self.label_66 = QLabel(self.b097)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(40, 143, 31, 16))
        self.label_66.setFont(font)
        self.label_66.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.byte097hbit5 = QCheckBox(self.b097)
        self.byte097hbit5.setObjectName(u"byte097hbit5")
        self.byte097hbit5.setEnabled(False)
        self.byte097hbit5.setGeometry(QRect(10, 143, 16, 16))
        self.label_64 = QLabel(self.b097)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(40, 55, 31, 16))
        self.label_64.setFont(font)
        self.tabWidget.addTab(self.b097, "")
        self.b098 = QWidget()
        self.b098.setObjectName(u"b098")
        self.line = QFrame(self.b098)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(23, 30, 20, 175))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_4 = QLabel(self.b098)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(11, 11, 230, 16))
        self.label_4.setFont(font)
        self.label_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_6 = QLabel(self.b098)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(40, 121, 789, 16))
        self.label_6.setFont(font)
        self.label_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.checkBox_CruiseLimit = QCheckBox(self.b098)
        self.checkBox_CruiseLimit.setObjectName(u"checkBox_CruiseLimit")
        self.checkBox_CruiseLimit.setGeometry(QRect(10, 121, 16, 16))
        self.label_27 = QLabel(self.b098)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(40, 143, 116, 16))
        self.label_27.setFont(font)
        self.label_27.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.byte098hbit5 = QCheckBox(self.b098)
        self.byte098hbit5.setObjectName(u"byte098hbit5")
        self.byte098hbit5.setEnabled(True)
        self.byte098hbit5.setGeometry(QRect(10, 143, 16, 16))
        self.label_28 = QLabel(self.b098)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(40, 165, 116, 16))
        self.label_28.setFont(font)
        self.label_28.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.byte098hbit6 = QCheckBox(self.b098)
        self.byte098hbit6.setObjectName(u"byte098hbit6")
        self.byte098hbit6.setEnabled(True)
        self.byte098hbit6.setGeometry(QRect(10, 165, 16, 16))
        self.label_29 = QLabel(self.b098)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(40, 187, 116, 16))
        self.label_29.setFont(font)
        self.label_29.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.byte098hbit7 = QCheckBox(self.b098)
        self.byte098hbit7.setObjectName(u"byte098hbit7")
        self.byte098hbit7.setEnabled(True)
        self.byte098hbit7.setGeometry(QRect(10, 187, 16, 16))
        self.label_25 = QLabel(self.b098)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(40, 33, 116, 16))
        self.label_25.setFont(font)
        self.byte098hbit0 = QCheckBox(self.b098)
        self.byte098hbit0.setObjectName(u"byte098hbit0")
        self.byte098hbit0.setGeometry(QRect(10, 33, 16, 16))
        self.label_26 = QLabel(self.b098)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(40, 55, 116, 16))
        self.label_26.setFont(font)
        self.byte098hbit1 = QCheckBox(self.b098)
        self.byte098hbit1.setObjectName(u"byte098hbit1")
        self.byte098hbit1.setGeometry(QRect(10, 55, 16, 16))
        self.label_5 = QLabel(self.b098)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 77, 793, 16))
        self.label_5.setFont(font)
        self.label_5.setToolTipDuration(-1)
        self.checkBox_MediaData = QCheckBox(self.b098)
        self.checkBox_MediaData.setObjectName(u"checkBox_MediaData")
        self.checkBox_MediaData.setEnabled(True)
        self.checkBox_MediaData.setGeometry(QRect(10, 77, 16, 16))
        self.checkBox_MediaData.setChecked(False)
        self.label_7 = QLabel(self.b098)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(40, 99, 739, 16))
        self.label_7.setFont(font)
        self.label_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.checkBox_ActiveGear = QCheckBox(self.b098)
        self.checkBox_ActiveGear.setObjectName(u"checkBox_ActiveGear")
        self.checkBox_ActiveGear.setGeometry(QRect(10, 99, 16, 16))
        self.tabWidget.addTab(self.b098, "")
        self.label_4.raise_()
        self.label_6.raise_()
        self.checkBox_CruiseLimit.raise_()
        self.label_27.raise_()
        self.byte098hbit5.raise_()
        self.label_28.raise_()
        self.byte098hbit6.raise_()
        self.label_29.raise_()
        self.byte098hbit7.raise_()
        self.label_25.raise_()
        self.byte098hbit0.raise_()
        self.label_26.raise_()
        self.byte098hbit1.raise_()
        self.label_5.raise_()
        self.checkBox_MediaData.raise_()
        self.label_7.raise_()
        self.checkBox_ActiveGear.raise_()
        self.line.raise_()
        self.b099 = QWidget()
        self.b099.setObjectName(u"b099")
        self.line_2 = QFrame(self.b099)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(23, 30, 20, 175))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.checkBox_Navi = QCheckBox(self.b099)
        self.checkBox_Navi.setObjectName(u"checkBox_Navi")
        self.checkBox_Navi.setGeometry(QRect(10, 33, 16, 16))
        self.label_10 = QLabel(self.b099)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(40, 55, 140, 16))
        self.label_10.setFont(font)
        self.label_10.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.checkBox_Oil = QCheckBox(self.b099)
        self.checkBox_Oil.setObjectName(u"checkBox_Oil")
        self.checkBox_Oil.setGeometry(QRect(10, 55, 16, 16))
        self.label_11 = QLabel(self.b099)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(40, 77, 130, 16))
        self.label_11.setFont(font)
        self.label_11.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.checkBox_trip = QCheckBox(self.b099)
        self.checkBox_trip.setObjectName(u"checkBox_trip")
        self.checkBox_trip.setGeometry(QRect(10, 77, 16, 16))
        self.label_12 = QLabel(self.b099)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(40, 99, 144, 16))
        self.label_12.setFont(font)
        self.label_12.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.checkBox_mileage = QCheckBox(self.b099)
        self.checkBox_mileage.setObjectName(u"checkBox_mileage")
        self.checkBox_mileage.setGeometry(QRect(10, 99, 16, 16))
        self.label_20 = QLabel(self.b099)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(40, 121, 77, 16))
        self.label_20.setFont(font)
        self.label_20.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_24 = QLabel(self.b099)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(11, 11, 233, 16))
        self.label_24.setFont(font)
        self.label_24.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_9 = QLabel(self.b099)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(40, 33, 149, 16))
        self.label_9.setFont(font)
        self.label_9.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.checkBox_temperature = QCheckBox(self.b099)
        self.checkBox_temperature.setObjectName(u"checkBox_temperature")
        self.checkBox_temperature.setEnabled(True)
        self.checkBox_temperature.setGeometry(QRect(10, 121, 16, 16))
        self.checkBox_temperature.setChecked(False)
        self.label_15 = QLabel(self.b099)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(40, 139, 67, 20))
        self.label_15.setFont(font)
        self.label_15.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.checkBox_Eco = QCheckBox(self.b099)
        self.checkBox_Eco.setObjectName(u"checkBox_Eco")
        self.checkBox_Eco.setEnabled(True)
        self.checkBox_Eco.setGeometry(QRect(10, 143, 16, 16))
        self.label_19 = QLabel(self.b099)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(40, 165, 201, 16))
        self.label_19.setFont(font)
        self.label_19.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.checkBox_MEM = QCheckBox(self.b099)
        self.checkBox_MEM.setObjectName(u"checkBox_MEM")
        self.checkBox_MEM.setEnabled(True)
        self.checkBox_MEM.setGeometry(QRect(10, 165, 16, 16))
        self.label_16 = QLabel(self.b099)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(40, 187, 252, 16))
        self.label_16.setFont(font)
        self.label_16.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.checkBox_CruiseLimitView = QCheckBox(self.b099)
        self.checkBox_CruiseLimitView.setObjectName(u"checkBox_CruiseLimitView")
        self.checkBox_CruiseLimitView.setEnabled(True)
        self.checkBox_CruiseLimitView.setGeometry(QRect(10, 187, 16, 16))
        self.tabWidget.addTab(self.b099, "")
        self.b09A = QWidget()
        self.b09A.setObjectName(u"b09A")
        self.line_10 = QFrame(self.b09A)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(23, 30, 20, 175))
        self.line_10.setFrameShape(QFrame.VLine)
        self.line_10.setFrameShadow(QFrame.Sunken)
        self.label_31 = QLabel(self.b09A)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(40, 187, 31, 16))
        self.label_31.setFont(font)
        self.label_31.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.byte09Ahbit7 = QCheckBox(self.b09A)
        self.byte09Ahbit7.setObjectName(u"byte09Ahbit7")
        self.byte09Ahbit7.setEnabled(True)
        self.byte09Ahbit7.setGeometry(QRect(10, 187, 16, 16))
        self.label_33 = QLabel(self.b09A)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(40, 165, 232, 16))
        self.label_33.setFont(font)
        self.label_33.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.byte09Ahbit6 = QCheckBox(self.b09A)
        self.byte09Ahbit6.setObjectName(u"byte09Ahbit6")
        self.byte09Ahbit6.setEnabled(True)
        self.byte09Ahbit6.setGeometry(QRect(10, 165, 16, 16))
        self.label_37 = QLabel(self.b09A)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(40, 121, 31, 16))
        self.label_37.setFont(font)
        self.byte09Ahbit4 = QCheckBox(self.b09A)
        self.byte09Ahbit4.setObjectName(u"byte09Ahbit4")
        self.byte09Ahbit4.setEnabled(True)
        self.byte09Ahbit4.setGeometry(QRect(10, 121, 16, 16))
        self.byte09Ahbit4.setChecked(False)
        self.label_32 = QLabel(self.b09A)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(40, 143, 256, 16))
        self.label_32.setFont(font)
        self.label_32.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.byte09Ahbit5 = QCheckBox(self.b09A)
        self.byte09Ahbit5.setObjectName(u"byte09Ahbit5")
        self.byte09Ahbit5.setEnabled(True)
        self.byte09Ahbit5.setGeometry(QRect(10, 143, 16, 16))
        self.byte09Ahbit0 = QCheckBox(self.b09A)
        self.byte09Ahbit0.setObjectName(u"byte09Ahbit0")
        self.byte09Ahbit0.setGeometry(QRect(10, 33, 16, 16))
        self.label_34 = QLabel(self.b09A)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(40, 55, 31, 16))
        self.label_34.setFont(font)
        self.byte09Ahbit1 = QCheckBox(self.b09A)
        self.byte09Ahbit1.setObjectName(u"byte09Ahbit1")
        self.byte09Ahbit1.setGeometry(QRect(10, 55, 16, 16))
        self.label_35 = QLabel(self.b09A)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(40, 77, 330, 16))
        self.label_35.setFont(font)
        self.byte09Ahbit2 = QCheckBox(self.b09A)
        self.byte09Ahbit2.setObjectName(u"byte09Ahbit2")
        self.byte09Ahbit2.setGeometry(QRect(10, 77, 16, 16))
        self.label_36 = QLabel(self.b09A)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(40, 99, 31, 16))
        self.label_36.setFont(font)
        self.byte09Ahbit3 = QCheckBox(self.b09A)
        self.byte09Ahbit3.setObjectName(u"byte09Ahbit3")
        self.byte09Ahbit3.setGeometry(QRect(10, 99, 16, 16))
        self.label_30 = QLabel(self.b09A)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(40, 33, 31, 16))
        self.label_30.setFont(font)
        self.label_38 = QLabel(self.b09A)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(11, 11, 215, 16))
        self.label_38.setFont(font)
        self.label_38.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.tabWidget.addTab(self.b09A, "")
        self.b09D = QWidget()
        self.b09D.setObjectName(u"b09D")
        self.line_3 = QFrame(self.b09D)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(23, 60, 20, 85))
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.label_43 = QLabel(self.b09D)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(11, 11, 229, 16))
        self.label_43.setFont(font)
        self.label_43.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_39 = QLabel(self.b09D)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(138, 34, 89, 16))
        self.label_39.setFont(font)
        self.theme = QComboBox(self.b09D)
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.setObjectName(u"theme")
        self.theme.setGeometry(QRect(11, 33, 100, 20))
        self.label_46 = QLabel(self.b09D)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(40, 62, 188, 16))
        self.label_46.setFont(font)
        self.clock = QCheckBox(self.b09D)
        self.clock.setObjectName(u"clock")
        self.clock.setEnabled(True)
        self.clock.setGeometry(QRect(11, 62, 16, 16))
        self.clock.setChecked(False)
        self.label_40 = QLabel(self.b09D)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(40, 84, 189, 16))
        self.label_40.setFont(font)
        self.label_40.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.startbutton = QCheckBox(self.b09D)
        self.startbutton.setObjectName(u"startbutton")
        self.startbutton.setGeometry(QRect(11, 84, 16, 16))
        self.label_45 = QLabel(self.b09D)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(40, 106, 31, 16))
        self.label_45.setFont(font)
        self.label_45.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.byte09Bhbit6 = QCheckBox(self.b09D)
        self.byte09Bhbit6.setObjectName(u"byte09Bhbit6")
        self.byte09Bhbit6.setGeometry(QRect(11, 106, 16, 16))
        self.label_41 = QLabel(self.b09D)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(40, 128, 31, 16))
        self.label_41.setFont(font)
        self.label_41.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.byte09Bhbit7 = QCheckBox(self.b09D)
        self.byte09Bhbit7.setObjectName(u"byte09Bhbit7")
        self.byte09Bhbit7.setGeometry(QRect(11, 128, 16, 16))
        self.tabWidget.addTab(self.b09D, "")
        self.b09C = QWidget()
        self.b09C.setObjectName(u"b09C")
        self.label_61 = QLabel(self.b09C)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(4, 11, 230, 16))
        self.label_61.setFont(font)
        self.label_61.setAlignment(Qt.AlignCenter)
        self.label_59 = QLabel(self.b09C)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(120, 33, 63, 16))
        self.label_59.setFont(font)
        self.bodytype = QComboBox(self.b09C)
        self.bodytype.addItem("")
        self.bodytype.addItem("")
        self.bodytype.addItem("")
        self.bodytype.addItem("")
        self.bodytype.setObjectName(u"bodytype")
        self.bodytype.setGeometry(QRect(10, 33, 100, 20))
        self.bodytype.setEditable(False)
        self.tabWidget.addTab(self.b09C, "")
        self.b09D_2 = QWidget()
        self.b09D_2.setObjectName(u"b09D_2")
        self.label_54 = QLabel(self.b09D_2)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(40, 165, 31, 16))
        self.label_54.setFont(font)
        self.label_54.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.byte09Dhbit6 = QCheckBox(self.b09D_2)
        self.byte09Dhbit6.setObjectName(u"byte09Dhbit6")
        self.byte09Dhbit6.setEnabled(True)
        self.byte09Dhbit6.setGeometry(QRect(10, 165, 16, 16))
        self.label_53 = QLabel(self.b09D_2)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(40, 187, 553, 16))
        self.label_53.setFont(font)
        self.label_53.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.checkBox_ParkAssist = QCheckBox(self.b09D_2)
        self.checkBox_ParkAssist.setObjectName(u"checkBox_ParkAssist")
        self.checkBox_ParkAssist.setEnabled(True)
        self.checkBox_ParkAssist.setGeometry(QRect(10, 187, 16, 16))
        self.label_50 = QLabel(self.b09D_2)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(11, 11, 230, 16))
        self.label_50.setFont(font)
        self.label_50.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_48 = QLabel(self.b09D_2)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(40, 33, 31, 16))
        self.label_48.setFont(font)
        self.label_48.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.byte09Dhbit4 = QCheckBox(self.b09D_2)
        self.byte09Dhbit4.setObjectName(u"byte09Dhbit4")
        self.byte09Dhbit4.setEnabled(True)
        self.byte09Dhbit4.setGeometry(QRect(10, 121, 16, 16))
        self.byte09Dhbit4.setChecked(False)
        self.label_51 = QLabel(self.b09D_2)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(40, 143, 183, 16))
        self.label_51.setFont(font)
        self.label_51.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.byte09Dhbit5 = QCheckBox(self.b09D_2)
        self.byte09Dhbit5.setObjectName(u"byte09Dhbit5")
        self.byte09Dhbit5.setEnabled(True)
        self.byte09Dhbit5.setGeometry(QRect(10, 143, 16, 16))
        self.byte09Dhbit0 = QCheckBox(self.b09D_2)
        self.byte09Dhbit0.setObjectName(u"byte09Dhbit0")
        self.byte09Dhbit0.setGeometry(QRect(10, 33, 16, 16))
        self.label_55 = QLabel(self.b09D_2)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(40, 55, 31, 16))
        self.label_55.setFont(font)
        self.label_55.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.byte09Dhbit1 = QCheckBox(self.b09D_2)
        self.byte09Dhbit1.setObjectName(u"byte09Dhbit1")
        self.byte09Dhbit1.setGeometry(QRect(10, 55, 16, 16))
        self.label_56 = QLabel(self.b09D_2)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(40, 77, 31, 16))
        self.label_56.setFont(font)
        self.label_56.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.byte09Dhbit2 = QCheckBox(self.b09D_2)
        self.byte09Dhbit2.setObjectName(u"byte09Dhbit2")
        self.byte09Dhbit2.setGeometry(QRect(10, 77, 16, 16))
        self.label_52 = QLabel(self.b09D_2)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(40, 99, 31, 16))
        self.label_52.setFont(font)
        self.label_52.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.byte09Dhbit3 = QCheckBox(self.b09D_2)
        self.byte09Dhbit3.setObjectName(u"byte09Dhbit3")
        self.byte09Dhbit3.setGeometry(QRect(10, 99, 16, 16))
        self.label_49 = QLabel(self.b09D_2)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(40, 121, 31, 16))
        self.label_49.setFont(font)
        self.label_49.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.line_11 = QFrame(self.b09D_2)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(23, 30, 20, 175))
        self.line_11.setFrameShape(QFrame.VLine)
        self.line_11.setFrameShadow(QFrame.Sunken)
        self.tabWidget.addTab(self.b09D_2, "")
        self.b09E = QWidget()
        self.b09E.setObjectName(u"b09E")
        self.label_60 = QLabel(self.b09E)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(11, 11, 229, 16))
        self.label_60.setFont(font)
        self.label_60.setAlignment(Qt.AlignCenter)
        self.label_58 = QLabel(self.b09E)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(130, 33, 92, 16))
        self.label_58.setFont(font)
        self.brand = QComboBox(self.b09E)
        self.brand.addItem("")
        self.brand.addItem("")
        self.brand.addItem("")
        self.brand.setObjectName(u"brand")
        self.brand.setGeometry(QRect(10, 33, 100, 20))
        self.tabWidget.addTab(self.b09E, "")
        self.journal = QPlainTextEdit(Form)
        self.journal.setObjectName(u"journal")
        self.journal.setGeometry(QRect(10, 420, 841, 251))
        self.journal.setFrameShape(QFrame.StyledPanel)
        self.journal.setFrameShadow(QFrame.Plain)
        self.journal.setTabChangesFocus(True)
        self.journal.setCenterOnScroll(False)
        self.label_14 = QLabel(Form)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 400, 98, 16))
        self.pushButtonAbout = QPushButton(Form)
        self.pushButtonAbout.setObjectName(u"pushButtonAbout")
        self.pushButtonAbout.setGeometry(QRect(10, 673, 93, 28))
        self.layoutWidget1 = QWidget(Form)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(15, 0, 351, 52))
        self.gridLayout_2 = QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.layoutWidget1)
        self.label.setObjectName(u"label")
        font1 = QFont()
        font1.setPointSize(8)
        font1.setKerning(False)
        self.label.setFont(font1)
        self.label.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)

        self.label_17 = QLabel(self.layoutWidget1)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setFont(font1)
        self.label_17.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_17, 0, 1, 1, 1)

        self.Port = QComboBox(self.layoutWidget1)
        self.Port.setObjectName(u"Port")

        self.gridLayout_2.addWidget(self.Port, 1, 0, 1, 1)

        self.Speed = QComboBox(self.layoutWidget1)
        self.Speed.addItem("")
        self.Speed.setObjectName(u"Speed")

        self.gridLayout_2.addWidget(self.Speed, 1, 1, 1, 1)

        self.ConnectButton = QPushButton(self.layoutWidget1)
        self.ConnectButton.setObjectName(u"ConnectButton")

        self.gridLayout_2.addWidget(self.ConnectButton, 1, 2, 1, 1)

        self.DisconnectButton = QPushButton(self.layoutWidget1)
        self.DisconnectButton.setObjectName(u"DisconnectButton")

        self.gridLayout_2.addWidget(self.DisconnectButton, 1, 3, 1, 1)

        self.layoutWidget2 = QWidget(Form)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(17, 56, 681, 98))
        self.gridLayout_3 = QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.ReadConfig = QPushButton(self.layoutWidget2)
        self.ReadConfig.setObjectName(u"ReadConfig")

        self.gridLayout_3.addWidget(self.ReadConfig, 0, 0, 1, 1)

        self.label_3 = QLabel(self.layoutWidget2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font1)
        self.label_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)

        self.hexValues = QLineEdit(self.layoutWidget2)
        self.hexValues.setObjectName(u"hexValues")

        self.gridLayout_3.addWidget(self.hexValues, 0, 2, 1, 1)

        self.SaveConfig = QPushButton(self.layoutWidget2)
        self.SaveConfig.setObjectName(u"SaveConfig")

        self.gridLayout_3.addWidget(self.SaveConfig, 0, 3, 1, 1)

        self.GetNewConfig = QPushButton(self.layoutWidget2)
        self.GetNewConfig.setObjectName(u"GetNewConfig")

        self.gridLayout_3.addWidget(self.GetNewConfig, 1, 0, 1, 1)

        self.label_13 = QLabel(self.layoutWidget2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setFont(font1)
        self.label_13.setAlignment(Qt.AlignCenter)

        self.gridLayout_3.addWidget(self.label_13, 1, 1, 1, 1)

        self.NewHexValues = QLineEdit(self.layoutWidget2)
        self.NewHexValues.setObjectName(u"NewHexValues")

        self.gridLayout_3.addWidget(self.NewHexValues, 1, 2, 1, 1)

        self.GetNewConfig_2 = QPushButton(self.layoutWidget2)
        self.GetNewConfig_2.setObjectName(u"GetNewConfig_2")
        self.GetNewConfig_2.setEnabled(False)

        self.gridLayout_3.addWidget(self.GetNewConfig_2, 1, 3, 1, 1)

        self.WriteConfig = QPushButton(self.layoutWidget2)
        self.WriteConfig.setObjectName(u"WriteConfig")

        self.gridLayout_3.addWidget(self.WriteConfig, 2, 0, 1, 1)


        self.retranslateUi(Form)

        self.tabWidget.setCurrentIndex(8)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0442\u043e\u0440 \u043c\u0430\u0442\u0440\u0438\u0447\u043d\u043e\u0433\u043e \u0434\u0438\u0441\u043f\u043b\u0435\u044f", None))
        self.label_67.setText(QCoreApplication.translate("Form", u"\u0421\u0432\u0435\u0434\u0435\u043d\u0438\u044f \u043e\u0431 \u043e\u0431\u043e\u0440\u0443\u0434\u043e\u0432\u0430\u043d\u0438\u0438", None))
#if QT_CONFIG(tooltip)
        self.label_68.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_68.setText(QCoreApplication.translate("Form", u"HW ID", None))
#if QT_CONFIG(tooltip)
        self.label_69.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_69.setText(QCoreApplication.translate("Form", u"Additional HW ID", None))
#if QT_CONFIG(tooltip)
        self.label_70.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_70.setText(QCoreApplication.translate("Form", u"SW ID", None))
#if QT_CONFIG(tooltip)
        self.label_71.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_71.setText(QCoreApplication.translate("Form", u"SW version", None))
#if QT_CONFIG(tooltip)
        self.label_72.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_72.setText(QCoreApplication.translate("Form", u"Date SW", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Form", u"Identification", None))
        self.label_47.setText(QCoreApplication.translate("Form", u"Byte 0x97h: unknown", None))
        self.label_44.setText(QCoreApplication.translate("Form", u"\u0431\u0438\u0442 2", None))
        self.byte097hbit2.setText("")
        self.label_62.setText(QCoreApplication.translate("Form", u"\u0431\u0438\u0442 7", None))
        self.byte097hbit0.setText("")
        self.byte097hbit4.setText("")
        self.label_42.setText(QCoreApplication.translate("Form", u"\u0431\u0438\u0442 6", None))
        self.byte097hbit6.setText("")
        self.byte097hbit7.setText("")
#if QT_CONFIG(tooltip)
        self.label_57.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_57.setText(QCoreApplication.translate("Form", u"\u0431\u0438\u0442 0", None))
        self.byte097hbit3.setText("")
        self.label_63.setText(QCoreApplication.translate("Form", u"\u0431\u0438\u0442 4", None))
        self.byte097hbit1.setText("")
        self.label_65.setText(QCoreApplication.translate("Form", u"\u0431\u0438\u0442 3", None))
        self.label_66.setText(QCoreApplication.translate("Form", u"\u0431\u0438\u0442 5", None))
        self.byte097hbit5.setText("")
        self.label_64.setText(QCoreApplication.translate("Form", u"\u0431\u0438\u0442 1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.b097), QCoreApplication.translate("Form", u"Byte 97h", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"List of available options (byte 0x98h):", None))
#if QT_CONFIG(tooltip)
        self.label_6.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>\u0414\u0430\u043d\u043d\u044b\u0439 \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440 \u0430\u043a\u0442\u0438\u0432\u0438\u0440\u0443\u0435\u0442 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0438\u043d\u0434\u0438\u043a\u0430\u0442\u043e\u0440\u0430 \u0440\u0430\u0431\u043e\u0442\u044b \u043a\u0440\u0443\u0438\u0437-\u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044f \u0438 \u043e\u0433\u0440\u0430\u043d\u0438\u0447\u0438\u0442\u0435\u043b\u044f \u0441\u043a\u043e\u0440\u043e\u0441\u0442\u0438</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_6.setText(QCoreApplication.translate("Form", u"CRUISE and LIMITER", None))
        self.checkBox_CruiseLimit.setText("")
        self.label_27.setText(QCoreApplication.translate("Form", u"bit 5 (unknown)", None))
        self.byte098hbit5.setText("")
        self.label_28.setText(QCoreApplication.translate("Form", u"bit 6 (unknown)", None))
        self.byte098hbit6.setText("")
        self.label_29.setText(QCoreApplication.translate("Form", u"bit 7 (unknown)", None))
        self.byte098hbit7.setText("")
        self.label_25.setText(QCoreApplication.translate("Form", u"Search for parking", None))
        self.byte098hbit0.setText("")
        self.label_26.setText(QCoreApplication.translate("Form", u"bit 1 (unknown)", None))
        self.byte098hbit1.setText("")
#if QT_CONFIG(tooltip)
        self.label_5.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" width=\"300\" cellspacing=\"2\" cellpadding=\"0\"><tr><td width=\"300\"><p>\u0414\u0430\u043d\u043d\u044b\u0439 \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440 \u0430\u043a\u0442\u0438\u0432\u0438\u0440\u0443\u0435\u0442 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u0435 \u0438\u0437 RT6/SMEG/NAC \u0434\u0430\u043d\u043d\u044b\u0445 \u043e \u0440\u0430\u0434\u0438\u043e/\u043c\u0435\u0434\u0438\u0430/\u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0435</p><p><br/><img src=\":/main_screen/images/main_screen.jpg\"/></p></td></tr></table></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_5.setText(QCoreApplication.translate("Form", u"Mediadata from multimedia", None))
        self.checkBox_MediaData.setText("")
#if QT_CONFIG(tooltip)
        self.label_7.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p> \u0414\u0430\u043d\u043d\u044b\u0439 \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440 \u0430\u043a\u0442\u0438\u0432\u0438\u0440\u0443\u0435\u0442 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0432 \u043f\u0440\u0430\u0432\u043e\u043c \u0432\u0435\u0440\u0445\u043d\u0435\u043c \u0443\u0433\u043b\u0443 \u0438\u043d\u0434\u0438\u043a\u0430\u0442\u043e\u0440\u0430 \u0442\u0435\u043a\u0443\u0449\u0435\u0439 \u043f\u0435\u0440\u0435\u0434\u0430\u0447\u0438</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_7.setText(QCoreApplication.translate("Form", u"GEAR index", None))
        self.checkBox_ActiveGear.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.b098), QCoreApplication.translate("Form", u"Byte 98h", None))
        self.checkBox_Navi.setText("")
        self.label_10.setText(QCoreApplication.translate("Form", u"Check oil level", None))
        self.checkBox_Oil.setText("")
        self.label_11.setText(QCoreApplication.translate("Form", u"Trips", None))
        self.checkBox_trip.setText("")
        self.label_12.setText(QCoreApplication.translate("Form", u"Mileage in bottom row", None))
        self.checkBox_mileage.setText("")
        self.label_20.setText(QCoreApplication.translate("Form", u"Temperature", None))
        self.label_24.setText(QCoreApplication.translate("Form", u"List of available options (byte 0x99h):", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"Navi from RT6/SMEG/NAC", None))
        self.checkBox_temperature.setText("")
        self.label_15.setText(QCoreApplication.translate("Form", u"\u0415\u0421\u041e", None))
        self.checkBox_Eco.setText("")
        self.label_19.setText(QCoreApplication.translate("Form", u"Activate MEM button", None))
        self.checkBox_MEM.setText("")
        self.label_16.setText(QCoreApplication.translate("Form", u"Top row with CRUISE and LIMITER indicator", None))
        self.checkBox_CruiseLimitView.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.b099), QCoreApplication.translate("Form", u"Byte 99h", None))
        self.label_31.setText(QCoreApplication.translate("Form", u"bit 7", None))
        self.byte09Ahbit7.setText("")
        self.label_33.setText(QCoreApplication.translate("Form", u"Time in settings", None))
        self.byte09Ahbit6.setText("")
        self.label_37.setText(QCoreApplication.translate("Form", u"bit 4", None))
        self.byte09Ahbit4.setText("")
        self.label_32.setText(QCoreApplication.translate("Form", u"Color themes in settings", None))
        self.byte09Ahbit5.setText("")
        self.byte09Ahbit0.setText("")
        self.label_34.setText(QCoreApplication.translate("Form", u"bit 1", None))
        self.byte09Ahbit1.setText("")
        self.label_35.setText(QCoreApplication.translate("Form", u"Language and mesuares value in settings", None))
        self.byte09Ahbit2.setText("")
        self.label_36.setText(QCoreApplication.translate("Form", u"bit 3", None))
        self.byte09Ahbit3.setText("")
        self.label_30.setText(QCoreApplication.translate("Form", u"bit 0", None))
        self.label_38.setText(QCoreApplication.translate("Form", u"List of available options (byte 0x9Ah):", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.b09A), QCoreApplication.translate("Form", u"Byte 9Ah", None))
        self.label_43.setText(QCoreApplication.translate("Form", u"List of available options (byte 0x9Bh):", None))
        self.label_39.setText(QCoreApplication.translate("Form", u"color theme", None))
        self.theme.setItemText(0, QCoreApplication.translate("Form", u"orange", None))
        self.theme.setItemText(1, QCoreApplication.translate("Form", u"black", None))
        self.theme.setItemText(2, QCoreApplication.translate("Form", u"techno black", None))
        self.theme.setItemText(3, QCoreApplication.translate("Form", u"blue", None))
        self.theme.setItemText(4, QCoreApplication.translate("Form", u"toffee", None))

        self.label_46.setText(QCoreApplication.translate("Form", u"Clock", None))
        self.clock.setText("")
        self.label_40.setText(QCoreApplication.translate("Form", u"Start/Stop", None))
        self.startbutton.setText("")
        self.label_45.setText(QCoreApplication.translate("Form", u"bit 6", None))
        self.byte09Bhbit6.setText("")
        self.label_41.setText(QCoreApplication.translate("Form", u"bit 7", None))
        self.byte09Bhbit7.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.b09D), QCoreApplication.translate("Form", u"Byte 9Bh", None))
        self.label_61.setText(QCoreApplication.translate("Form", u"List of available options (byte 0x9Ch):", None))
        self.label_59.setText(QCoreApplication.translate("Form", u"bodytype", None))
        self.bodytype.setItemText(0, QCoreApplication.translate("Form", u"10 - hatch", None))
        self.bodytype.setItemText(1, QCoreApplication.translate("Form", u"20 - sedan", None))
        self.bodytype.setItemText(2, QCoreApplication.translate("Form", u"30 - wagon", None))
        self.bodytype.setItemText(3, QCoreApplication.translate("Form", u"40 - other (sedan)", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.b09C), QCoreApplication.translate("Form", u"Byte 9Ch", None))
        self.label_54.setText(QCoreApplication.translate("Form", u"bit 6", None))
        self.byte09Dhbit6.setText("")
#if QT_CONFIG(tooltip)
        self.label_53.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>\u0414\u0430\u043d\u043d\u044b\u0439 \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440 \u0430\u043a\u0442\u0438\u0432\u0438\u0440\u0443\u0435\u0442 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u043f\u0430\u0440\u043a\u0442\u0440\u043e\u043d\u0438\u043a\u043e\u0432 \u043d\u0430 \u0434\u0438\u0441\u043f\u043b\u0435\u0435</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_53.setText(QCoreApplication.translate("Form", u"Park assist", None))
        self.checkBox_ParkAssist.setText("")
        self.label_50.setText(QCoreApplication.translate("Form", u"List of available options (byte 0x9Dh):", None))
        self.label_48.setText(QCoreApplication.translate("Form", u"bit 0", None))
        self.byte09Dhbit4.setText("")
        self.label_51.setText(QCoreApplication.translate("Form", u"4WD (maybe for electric car)", None))
        self.byte09Dhbit5.setText("")
        self.byte09Dhbit0.setText("")
        self.label_55.setText(QCoreApplication.translate("Form", u"bit 1", None))
        self.byte09Dhbit1.setText("")
        self.label_56.setText(QCoreApplication.translate("Form", u"bit 2", None))
        self.byte09Dhbit2.setText("")
        self.label_52.setText(QCoreApplication.translate("Form", u"bit 3", None))
        self.byte09Dhbit3.setText("")
        self.label_49.setText(QCoreApplication.translate("Form", u"bit 4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.b09D_2), QCoreApplication.translate("Form", u"Byte 9Dh", None))
        self.label_60.setText(QCoreApplication.translate("Form", u"List of available options (byte 0x9Eh):", None))
        self.label_58.setText(QCoreApplication.translate("Form", u"logo", None))
        self.brand.setItemText(0, QCoreApplication.translate("Form", u"Citroen", None))
        self.brand.setItemText(1, QCoreApplication.translate("Form", u"DS", None))
        self.brand.setItemText(2, QCoreApplication.translate("Form", u"Peugeot", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.b09E), QCoreApplication.translate("Form", u"Byte 9Eh", None))
        self.journal.setPlainText(QCoreApplication.translate("Form", u"Welcome!\n"
"\n"
"", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"Journal", None))
        self.pushButtonAbout.setText(QCoreApplication.translate("Form", u"About", None))
        self.label.setText(QCoreApplication.translate("Form", u"COM-port", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"Speed", None))
        self.Speed.setItemText(0, QCoreApplication.translate("Form", u"125000", None))

        self.ConnectButton.setText(QCoreApplication.translate("Form", u"Connect", None))
        self.DisconnectButton.setText(QCoreApplication.translate("Form", u"Disconnect", None))
        self.ReadConfig.setText(QCoreApplication.translate("Form", u"Read config", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Current config (HEX)", None))
        self.hexValues.setText("")
        self.SaveConfig.setText(QCoreApplication.translate("Form", u"Save to file", None))
        self.GetNewConfig.setText(QCoreApplication.translate("Form", u"Prepare new config", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"New config (HEX)", None))
        self.NewHexValues.setText("")
        self.GetNewConfig_2.setText(QCoreApplication.translate("Form", u"Load from file", None))
        self.WriteConfig.setText(QCoreApplication.translate("Form", u"Telecoding", None))
    # retranslateUi_eng

